# Root logger
rootLogger.level = ERROR
rootLogger.appenderRef.console.ref = Console

# Console Appender
appender.console.type = Console
appender.console.name = Console
# appender.console.layout.type = PatternLayout
# appender.console.layout.pattern = %m%n

# Reduce Flink logging
logger.flink.name = org.apache.flink
logger.flink.level = ERROR

# Reduce Kafka logging
logger.kafka.name = org.apache.kafka
logger.kafka.level = ERROR

# Reduce Pekko/Akka logging
logger.pekko.name = org.apache.pekko
logger.pekko.level = ERROR

# Reduce Hadoop logging
logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = ERROR